const TEAM_OWNER_ROLE = "owner";
const TEAM_ADMIN_ROLE = "admin";
const TEAM_MEMBER_ROLE = "member";

const SESSION_ROLES = [TEAM_OWNER_ROLE, TEAM_ADMIN_ROLE, TEAM_MEMBER_ROLE];
const INVITABLE_ROLES = [TEAM_ADMIN_ROLE, TEAM_MEMBER_ROLE];

module.exports = {
  TEAM_OWNER_ROLE,
  TEAM_ADMIN_ROLE,
  TEAM_MEMBER_ROLE,
  SESSION_ROLES,
  INVITABLE_ROLES,
};
