const PASSWORD_RESET_TOKEN_TYPE = "atlas_password_reset";
const PASSWORD_RESET_TTL_MINUTES = 15;
const PASSWORD_RESET_TTL_JWT = "15m";

module.exports = {
  PASSWORD_RESET_TOKEN_TYPE,
  PASSWORD_RESET_TTL_MINUTES,
  PASSWORD_RESET_TTL_JWT,
};
